feat: available garages, filters and my rentals #10
Aparking/AparKing_Frontend pull request #14
Opened 2024-03-09 21:05 UTC by silvglad

Tarea referenciada: https://github.com/Aparking/AparKing_Backend/issues/10
Realizada por: @silvglad 
Resumen: Se implementa dentro del Tab2 la vista de todos los alquileres disponibles de todos los usuarios. Dentro de la misma vista, hay tres tipos de filtros: por nombre, por precio y por dimensiones. La lista de alquileres se actualiza reactivamente con los filtros y la vista se ha adaptado a móviles.
En la misma vista, se implementan dos botones en la parte inferior: 
- La vista de todos los garajes para un admin, realizado por @laurolmer en https://github.com/Aparking/AparKing_Backend/issues/11 . Como aún no se ha implementado la autenticación ni el inicio de sesión en la aplicación, no se comprueban los permisos aún.

2024-03-09 22:04 UTC, laurolmer approved these changes
Parece estar todo en orden, buen trabajo Enkirre 🧇

2024-03-09 22:14 UTC, laurolmer approved these changes
Parece estar en orden, sin embargo, quizás estaría bien agregar algún filtro adicional, como que se puedan ver los alquileres que hay por X ciudad específica. Bien trabajado estimado compañero 🧇.

2024-03-09 22:23 UTC, laurolmer requested changes
Quizás estaría bien agregar algún filtro adicional, como que se puedan ver los alquileres que hay por X ciudad específica. También estaría bien que lanzara una excepción en caso de no haber encontrado ningún resultado con los filtros aplicados. 

Además, parece ser que no termina de mostrar bien el listado, ya que salta este fallo:
![image](https://github.com/Aparking/AparKing_Frontend/assets/73184962/f3071508-d14e-47a6-a4a5-a39916b85630)

2024-03-10 12:58 UTC, laurolmer approved these changes
Se ha realizado una rama fix para arreglar los fallos de dependencia, te doy el ok para esta rama y continúa en esa nueva rama https://github.com/Aparking/AparKing_Frontend/tree/fix/rental-parts-merger/15

2024-03-10 13:05 UTC, 3ralon approved these changes
Okey, tal y como comenta @laurolmer puedes continuar con los cambios en la rama que ha hecho ya que está todo unido en el mismo componente.

2024-03-10 13:10 UTC, merged