Feat/pricing plans/12
Aparking/AparKing_Frontend pull request #19
Opened 2024-03-10 16:17 UTC by PedroRuizAguilar

Hemos implementado @JoseJavierAlcobendas y yo los pricing-plan del usuario en la url: /pricing-plan hemos mejorado tambien el login del usuario y ahora hay una funcionalidad para obtener el usuario que esta loggeado

2024-03-10 16:18 UTC, JoseJavierAlcobendas approved these changes
Muy bonito la vista de planes de precio y es muy útil el poder obtener el usuario logueado

2024-03-11 21:47 UTC, 3ralon requested changes
En general los cambios no están mal. Sin embargo, corregid algunas líneas que hacen ruido en develop y que disminuyen la calidad del código. 🪐👽

2024-03-11 21:47 UTC, 3ralon commented on angular.json
@PedroRuizAguilar @JoseJavierAlcobendas por qué habés añadido esta línea??

2024-03-11 21:47 UTC, 3ralon commented on src/app/service/pricing-plan.service.ts
Deberíais cambiar el método del servicio al archivo [rest.service.ts](https://github.com/Aparking/AparKing_Frontend/blob/main/src/app/service/rest.service.ts) que es donde están todos los servicios definidos.

2024-03-11 21:47 UTC, 3ralon commented on src/app/service/register.service.ts
Los métodos de este servicio también deberíais moverlos al [rest.service.ts](https://github.com/Aparking/AparKing_Frontend/blob/main/src/app/service/rest.service.ts).

2024-03-11 21:47 UTC, 3ralon commented on src/app/components/pricing-plan/pricing-plan.component.ts
Quizás estaría mejor que no dejasemos los `console.log();` por ahí desperdigados. Dejad únicamente los de error `console.error()`.

2024-03-11 21:47 UTC, 3ralon commented on src/app/tab2/tab2.module.ts
¿Por qué habéis añadido el módulo de autenticación al tab2?

2024-03-12 16:16 UTC, laurolmer requested changes
El cambio de créditos y permisos tras el pago pertenece a otra tarea, lo habéis solapado. Aparte, quizás es un poco más recomendable esperar a que @JuanCarlosRL y @alepervaz  hagan su tarea de la pasarela de pago.

2024-03-19 16:57 UTC, sergiosant02 requested changes
Debeis de aplicar todas las sugerencias, debido a que hay lagunas cosas, unas mas que otras que de seguir así complicarían más el desarrollo, no vamos sobrados de tiempo, es una inversión para no perderlo más adelante.

2024-03-19 16:57 UTC, sergiosant02 commented on src/app/service/login.service.ts
Este archivo tiene dos errores principales:
1.(GRAVE)-> Ya he comentado en persona que en este tipo de proyectos las peticiones http tienen una estructura, es inadmisible que llaméis a http directamente desde el servicio, principalmente porque desajustáis todo el desarrollo, lo hacemos así no solo para evitar posibles errores, sino para agilizar los sucesivos desarrollos, al igual que facilitar los cambios de entornos necesarios para el despliegue por ejemplo. Tenéis un ejemplo de como debe hacerse en master y en develop. 

2.(MEDIO)-> no useis "any" estamos en typescript tenemos la ventaja de que podemos tirar todo cuanto queramos, currentUser esta claro de que tipo va a ser, no hay necesidad de emplear "any" solo va a dar lugar a más errores y peor código.

2024-03-19 16:57 UTC, sergiosant02 commented on src/app/service/pricing-plan.service.ts
Este archivo tiene un gran error:
1.(GRAVE)-> Ya he comentado en persona que en este tipo de proyectos las peticiones http tienen una estructura, es inadmisible que llaméis a http directamente desde el servicio, principalmente porque desajustáis todo el desarrollo, lo hacemos así no solo para evitar posibles errores, sino para agilizar los sucesivos desarrollos, al igual que facilitar los cambios de entornos necesarios para el despliegue por ejemplo. Tenéis un ejemplo de como debe hacerse en master y en develop.

2024-03-19 16:57 UTC, sergiosant02 commented on src/app/service/register.service.ts
Este archivo tiene un error
1.(GRAVE)-> Ya he comentado en persona que en este tipo de proyectos las peticiones http tienen una estructura, es inadmisible que llaméis a http directamente desde el servicio, principalmente porque desajustáis todo el desarrollo, lo hacemos así no solo para evitar posibles errores, sino para agilizar los sucesivos desarrollos, al igual que facilitar los cambios de entornos necesarios para el despliegue por ejemplo. Tenéis un ejemplo de como debe hacerse en master y en develop.

2024-03-19 16:57 UTC, sergiosant02 commented on src/app/models/user.models.ts
Como ya he comentado en otro archivo, no uséis any, observad que recibís de la api del backend y estableces el tipo en base a esto, si es un timeStamp hacéis una conversión en el frontend y si es un date pues un date.
Si lo habéis hecho por alguna razón en concreto podéis comentarlo también

2024-03-19 16:57 UTC, sergiosant02 commented on src/app/models/user.models.ts
Hasta ahora no me consta que necesitemos dos tipos User, en esencia, menos aun cuando los dos que habéis declarado, uno ya estaba, son casi iguales, si habéis requerido de algún campo extra añadidlo, no creéis una entidad nueva.

2024-03-20 09:00 UTC, alepervaz commented
> El cambio de créditos y permisos tras el pago pertenece a otra tarea, lo habéis solapado. Aparte, quizás es un poco más recomendable esperar a que @JuanCarlosRL y @alepervaz hagan su tarea de la pasarela de pago.

No se pero creo que seria mas idóneo que una vez se haya implementado los planes de pago, se desarrolle la pasarela, puesto que desde mi punto de vista no tiene mucho que podamos pagar algo que no esta implementado

2024-03-23 22:48 UTC, laurolmer commented on src/app/components/pricing-plan/pricing-plan.component.ts
> +        price = 30.99;
El coste de los planes de precio no eran otros?

2024-04-01 19:35 UTC, CarmenRuizPorcel approved these changes
Perfecto Pedro muy chulo. Me gusta la idea del plan más vendido.
Hay que ceñirse un poco más a los mockup, pero entiendo tu batalla con ionic
Cuando se añada a la épica, se se pueda acceder a los precios desde la tap 3 (que por ahora no se está usando, será la de usuario en S3)

2024-04-01 19:36 UTC, laurolmer approved these changes
****

2024-04-01 19:37 UTC, marvicmar approved these changes
Ahora sí esta correcto, se han realizado todos los cambios solicitados. Buen trabajo.

2024-04-01 19:37 UTC, merged