Añadir, editar y eliminar usuarios desde admin [Frontend]
Aparking/AparKing_Frontend pull request #20
Opened 2024-03-11 20:07 UTC by IsmaelRuizJurado

#4 
Funcionalidad base añadida con validaciones básicas.
Cosas que sé que faltan (posiblemente implementarlas en un futuro cercano):
-Que las acciones sean realizables por un admin (pues no contaba con la funcionalidad de login)
-Restricción sobre fecha para la mayoría de edad de los usuarios
-Refactorización general
-Cambiar los estilos para que sean acordes al resto de la aplicación

Para probar la funcionalidad:
En front, usar la ruta users. Clicar sobre el nombre de un usuario para probar las funcionalidades de actualizar y borrar.
Para añadir un nuevo usuario usar la ruta add.

2024-03-11 21:32 UTC, IsmaelRuizJurado commented
Conflictos solucionados.

2024-03-12 08:03 UTC, JoseJavierAlcobendas requested changes
Se que sabes que te falta refactorizar y los estilos sin embargo lo suyo sería que lo hicieses en esta pull request y en cuanto a la funcionalidad de añadir un user porque no pones un boton en el listado de usuarios que te lleve a la url /add.
Por lo demas muy buen trabajo!!

2024-03-12 08:29 UTC, virolialo requested changes
Las pantallas funcionan bien, aunque estoy con Jose, hace falta refactorizar código.

También habría que crear una carpeta raíz para los componentes de usuario, y ahí meter todas las que se han ido creado relacionados con este, pero esto se podría solucionar una vez se integre todo en la épica de la gestión de usuario.

Buen trabajo Ismael 👍

2024-03-13 11:52 UTC, IsmaelRuizJurado commented
He añadido el botón mencionado y he realizado una pequeña refactorización del código de los componentes. En cuanto a los estilos he decidido dejarlos con los predeterminados de ionic para más tarde cambiarlos según el resto de implementaciones.

2024-03-15 14:32 UTC, laurolmer approved these changes
lo veo bien

2024-03-16 11:13 UTC, 3ralon approved these changes
Lo veo bien @IsmaelRuizJurado, te acepto los cambios 😺

2024-03-19 15:29 UTC, JoseJavierAlcobendas approved these changes

2024-03-31 16:28 UTC, virolialo approved these changes
Todo en orden !! Me alegra que hayas seguido en consejo :)

2024-03-31 16:29 UTC, merged