Creación de garaje e imágenes asociadas
Aparking/AparKing_Frontend pull request #21
Opened 2024-03-11 21:38 UTC by ivasansan1

Tarea referenciada: https://github.com/Aparking/AparKing_Backend/issues/8
Realizada por: @ivasansan1
Resumen: Este código implementa la creación de anuncios para garajes incluyendo las imágenes y la dirección.  El formulario está dividido en la creación del garaje y posteriormente  el formulario de las imágenes.

- Pd: he dejado comentado una parte del código para una futura implementación de unificación de los formularios.
- Pd2: hay que hacer que el Ower no pueda ser elegible. Es una implementación que se hará cuando se realice el inicio de sesión

2024-03-11 22:06 UTC, perealberto requested changes
Okey @ivasansan1, no lo veo mal. Sin embargo, hay que tener cuidado a la hora de hacer merge porque en la épica tenemos la configuración de enrutado de los tabs, que es un poco sensible a cambios 😭. Por tanto, te solicito el cambio para que en tu rama resolvamos los cambios, que te podemos ayudar @laurolmer y yo, que estuvimos configurándolo y nos aseguramos de no desconfigurar la épica.

2024-03-11 22:06 UTC, perealberto commented on angular.json
Por qué has incluido esta línea??

2024-03-17 21:55 UTC, ivasansan1 commented
He arreglado el tab2 y he optimizado el formulario para que se haga todo en uno solo. Deseo que sea de su agrado los cambios @3ralon ♥

2024-03-17 22:02 UTC, 3ralon approved these changes
Okey, ahora ya está dentro del tab2, perfecto! 😄

2024-03-17 22:21 UTC, laurolmer approved these changes
Se ve tela de bien, bien hecho Iván 😵‍💫

2024-03-17 22:21 UTC, merged