Feat/social media/30
Aparking/AparKing_Frontend pull request #32
Opened 2024-04-06 18:05 UTC by JoseJavierAlcobendas

Añadido icono de Instagram y gmail en la pagina de Sobre Nosotros, al hacer clic te lleva a la cuenta de instagram o a gmail para escribir un correo.

2024-04-06 23:00 UTC, laurolmer requested changes
Dos cosas. La primera es que creo que deberíais de implementar el apartado de aceptar las cookies, ya que nuestra app maneja datos personales y tal. La segunda es que esta PR es lo mismo que la de Pedro, no?

2024-04-07 09:03 UTC, JoseJavierAlcobendas commented
Respondiendote a lo que has dicho, mi tarea era poner las redes sociales en la aplicación y pense que donde mejor iban a estar era en la página de About Us que era la tarea de @PedroRuizAguilar. Y con respecto a las cookies esa tarea no esta asignada a nosotros y no creo que este bien implementarla cuando accedas a la página de información sino que salga en la principal tras haber hecho el login pero no se como esta detallada esa tarea

2024-04-07 19:22 UTC, marvicmar requested changes
Esta tarea debe mergearse primero a su épica correspondiente en lugar de a develop

2024-04-08 14:38 UTC, laurolmer approved these changes
Viendo el comentario de @JoseJavierAlcobendas me ha quedado claro, sin embargo, digo lo mismo que he dicho en la otra PR.

2024-04-08 18:53 UTC, JoseJavierAlcobendas commented
> Esta tarea debe mergearse primero a su épica correspondiente en lugar de a develop

Y donde esta creada la epica de estas tareas, o hay que crear una especifica?

2024-04-08 19:47 UTC, laurolmer commented
cread una específica que englobe vuestras 2 tareas, algo tipo epic/app-information/27

2024-04-09 08:47 UTC, CarmenRuizPorcel approved these changes
Genial Jose, buen trabajo ✨

2024-04-09 08:52 UTC, ivasansan1 approved these changes
bien currao señores se ve flama

2024-04-09 20:21 UTC, merged