Feat: About us page #28
Aparking/AparKing_Frontend pull request #33
Opened 2024-04-06 18:07 UTC by PedroRuizAguilar

Se añade la pagina de about us se accede desde url simplemente poniendo /about-us

2024-04-06 22:58 UTC, laurolmer approved these changes
Se ve bien

2024-04-06 23:01 UTC, laurolmer requested changes
Lo mismo que he dicho en la PR de @JoseJavierAlcobendas

2024-04-07 10:17 UTC, PedroRuizAguilar commented
Lo que comento @JoseJavierAlcobendas realmente no nos dijeron nada de cookies 🍪.

2024-04-07 19:24 UTC, marvicmar requested changes
Al igual que a @JoseJavierAlcobendas Debe mergearse primero a la épica correspondiente y después a develop. Respecto a lo de @laurolmer no entiendo que quiere decir con lo de las cookies la verdad, no le veo el sentido en esta página de contactos de AparKing.

2024-04-07 19:51 UTC, CarmenRuizPorcel commented
La cookies se deberián aceptar cuando te registras ¿no?

> Al igual que a @JoseJavierAlcobendas Debe mergearse primero a la épica correspondiente y después a develop. Respecto a lo de @laurolmer no entiendo que quiere decir con lo de las cookies la verdad, no le veo el sentido en esta página de contactos de AparKing.

2024-04-08 14:36 UTC, laurolmer commented
> Las cookies se deberián aceptar cuando te registras ¿no?
> 
> > Al igual que a @JoseJavierAlcobendas Debe mergearse primero a la épica correspondiente y después a develop. Respecto a lo de @laurolmer no entiendo que quiere decir con lo de las cookies la verdad, no le veo el sentido en esta página de contactos de AparKing.

Sí, pero no sé hasta que punto se ha contemplado en las issues o no

2024-04-08 14:37 UTC, laurolmer commented
Respecto a lo otro, oki, os levanto el request for changes entonces

2024-04-08 14:37 UTC, laurolmer approved these changes

2024-04-08 16:37 UTC, CarmenRuizPorcel commented
> > Las cookies se deberián aceptar cuando te registras ¿no?
> > > Al igual que a @JoseJavierAlcobendas Debe mergearse primero a la épica correspondiente y después a develop. Respecto a lo de @laurolmer no entiendo que quiere decir con lo de las cookies la verdad, no le veo el sentido en esta página de contactos de AparKing.
> 
> Sí, pero no sé hasta que punto se ha contemplado en las issues o no

Pues habría que abrir una nueva issue para hacer lo de las cookies en el registro, no va a suponer mucho retardo creo yo. Solo será una check box en el formulario y un enlace a las cookies

2024-04-08 16:48 UTC, MarioArocaPaez commented
> > > Las cookies se deberián aceptar cuando te registras ¿no?
> > > > Al igual que a @JoseJavierAlcobendas Debe mergearse primero a la épica correspondiente y después a develop. Respecto a lo de @laurolmer no entiendo que quiere decir con lo de las cookies la verdad, no le veo el sentido en esta página de contactos de AparKing.
> > 
> > 
> > Sí, pero no sé hasta que punto se ha contemplado en las issues o no
> 
> Pues habría que abrir una nueva issue para hacer lo de las cookies en el registro, no va a suponer mucho retardo creo yo. Solo será una check box en el formulario y un enlace a las cookies

Yo tengo que hacer ya eso con el CA y las leyes, supongo que podría poner lo de las Cookies también

https://github.com/Aparking/AparKing_Backend/issues/29

2024-04-09 08:14 UTC, CarmenRuizPorcel commented
@PedroRuizAguilar Cread una épica para esto, seguid la guía de código del docusaurus por favor :bowtie:

2024-04-09 08:27 UTC, CarmenRuizPorcel commented
https://base-conocimiento-g11.vercel.app/docs/Planificaci%C3%B3n%20proyecto/Gesti%C3%B3n%20de%20la%20Configuraci%C3%B3n

2024-04-09 08:30 UTC, PedroRuizAguilar commented
Ya he cambiado la rama base de la pull request a la rama epica epic/app-information

2024-04-09 08:45 UTC, CarmenRuizPorcel approved these changes
Genial Pedro, buen trabajo 👌

2024-04-09 20:21 UTC, merged