Implementacion de pasarela de pago para la membresia
Aparking/AparKing_Frontend pull request #34
Opened 2024-04-07 18:17 UTC by alepervaz

Implementación de pasarela de pago que incluye la lógica mediante la cual se otorga a los usuarios los créditos y los permisos necesarios
![Captura de pantalla 2024-04-07 200532](https://github.com/Aparking/AparKing_Frontend/assets/73081268/962064fa-0f0f-4d2c-b58d-3101f0b412c4)
![Captura de pantalla 2024-04-07 200607](https://github.com/Aparking/AparKing_Frontend/assets/73081268/8eeda80b-1274-49e9-80ba-a895c8149ce5)
![Captura de pantalla 2024-04-07 200523](https://github.com/Aparking/AparKing_Frontend/assets/73081268/0a9d5d50-b1f8-405e-abd8-c4395d1a9912)

2024-04-07 19:25 UTC, marvicmar requested changes
Has cometido un error respecto a la rama a la que quieres mergearla, no puede ir a master directamente sino a su épica correspondiente y posteriormente a develop. Comprendo que ha sido un error, edita la issue si puedes.

2024-04-08 04:26 UTC, sergiosant02 requested changes
El incremente que propones es muy bueno, enhorabuena!!!
Solo te he dejado un comentario pequeño, échale un ojo, si quieres lo discutimos y vemos lo que quieras

2024-04-08 04:26 UTC, sergiosant02 commented on src/app/service/data-management.service.ts
- Debes hacer las llamadas a dataManagementService, no ha restService, es un cambio sencillo, es más que nada por semántica, el restService contiene las urls pero el dataManagement se encarga de gestionar las llamadas dando una capa de abstracción. Cámbialo si no te importa.
- Se ha colado un console.log, eliminalo por favor.

2024-04-08 09:37 UTC, alepervaz commented on src/app/service/data-management.service.ts
ya lo he resuelto, cuando tengas un momento revísalo si puedes :)

2024-04-08 14:35 UTC, laurolmer approved these changes
Se ve tela de fresco @alepervaz buen curro

2024-04-08 15:23 UTC, 3ralon approved these changes
Lo veo bien @alepervaz, gran trabajo! ⭐

2024-04-09 08:16 UTC, CarmenRuizPorcel approved these changes
Se ve genial 😄 
Muy buen trabajo Ale

2024-04-09 20:22 UTC, merged