Crear disponibilidad y alquilar por usuarios
Aparking/AparKing_Frontend pull request #36
Opened 2024-04-08 23:43 UTC by 3ralon

Añade la funcionalidad correspondiente a crear disponibilidades por el usuario, así como reservar una plaza de alquiler y/o cancelarla.

2024-04-09 06:05 UTC, laurolmer approved these changes
Lo veo bien pero quizás va a haber que observar si tiene conflictos con los cambios que tengo que añadir

2024-04-09 08:10 UTC, 3ralon commented
> Lo veo bien pero quizás va a haber que observar si tiene conflictos con los cambios que tengo que añadir

Bueno sí, pero esos conflictos se resolverán cuando hagas la pull request a la épica jeje

2024-04-09 08:19 UTC, CarmenRuizPorcel requested changes
Hay un problema con el despliegue en vercel, habla con @sergiosant02 que tiene la consola de vercel para que te pase el error porque se está subiendo algo que hace que pete el frontend :hushed:

2024-04-11 15:25 UTC, MarioArocaPaez approved these changes

2024-04-12 21:05 UTC, CarmenRuizPorcel approved these changes
Genial, problema resuelto

2024-04-12 21:05 UTC, merged