fix: feedback s3 #337
Aparking/AparKing_Frontend pull request #85
Opened 2024-05-13 18:31 UTC by virolialo

Se ha realizado todo lo pedido para la tarea #337, donde se pedía cambiar algunos estilos. Estos son:

- Planes de las subscripciones.
- About-Us
- Formularios de registrar vehículo, perfil de usuario y añadir garaje.
- Pop-Up de mis reservas y mis garajes.

2024-05-14 10:32 UTC, MarioArocaPaez approved these changes
Guay, muy buen trabajo, pero tienes que resolver los conflictos con develop antes :(

2024-05-15 08:30 UTC, CarmenRuizPorcel commented
@virolialo te tengo que llamar la atención, porque estás incumpliendo la clausula de seguir los estandares de configuración.
El commits que has hecho no sigue ninguna de las tags del documento [Gestion de la configuración](https://base-conocimiento-g11.vercel.app/docs/Planificaci%C3%B3n%20proyecto/Gesti%C3%B3n%20de%20la%20Configuraci%C3%B3n) además que no estás siguiendo las buenas practicas a la hora de hacer commits. Deben ser comits atómicos (un commit por cada feature que hagas) y además tiene que tener un nombre que permita entender que se ha cambiado (Feedback no explica nada)
Te aviso para próximas aportaciones al proyecto, porque es importante que el estilo de los commits este unificado 😄

2024-05-15 09:38 UTC, marvicmar commented
@MarioArocaPaez Sí hay conflictos no lo apruebes se lo dejas como rechazado o comentado hasta que se solucione porfi, por seguridad

2024-05-15 09:40 UTC, MarioArocaPaez commented
> @MarioArocaPaez Sí hay conflictos no lo apruebes se lo dejas como rechazado o comentado hasta que se solucione porfi, por seguridad

Si, perdón le di rápido sin querer y ahora no me deja cambiar el estado. Tendré mas cuidado :skull:

2024-05-15 09:41 UTC, marvicmar requested changes
Soluciona antes los conflictos del merge y subelo. Por otro lado, comentarte si has tenido en cuenta la vista móvil para los cambios de estilos, sobre todo de los formularios.

2024-05-15 09:41 UTC, MarioArocaPaez requested changes
Resuelve el conflicto antes de nada pls

2024-05-15 10:30 UTC, virolialo commented
> @virolialo te tengo que llamar la atención, porque estás incumpliendo la clausula de seguir los estandares de configuración. El commits que has hecho no sigue ninguna de las tags del documento [Gestion de la configuración](https://base-conocimiento-g11.vercel.app/docs/Planificaci%C3%B3n%20proyecto/Gesti%C3%B3n%20de%20la%20Configuraci%C3%B3n) además que no estás siguiendo las buenas practicas a la hora de hacer commits. Deben ser comits atómicos (un commit por cada feature que hagas) y además tiene que tener un nombre que permita entender que se ha cambiado (Feedback no explica nada) Te aviso para próximas aportaciones al proyecto, porque es importante que el estilo de los commits este unificado 😄

Buenas Carmen tienes razón, el commit es demasiado grande y tiene muy poco contexto de qué se ha realizado. Para la próxima ocasión haré commits por secciones trabajadas en la tarea, para que sea más fácil de identificar en qué se ha ido trabajando a lo largo del PR.

Igualmente, para evitar confusiones, cuando solucione los conflictos actuales con la implementación de las validaciones de María, voy a elaborar una descripción más desarrollada de todos los cambios implementados durante el commit.

Muchas gracias por la aclaración !!

2024-05-15 10:31 UTC, virolialo commented
> Resuelve el conflicto antes de nada pls

Eso está hecho !! Lo resuelvo y como he comentado en otro comentario a Carmen, haré una descripción más detallada de los cambios para evitar confusión con lo implementado :)

2024-05-15 12:01 UTC, virolialo commented
Buenas! Ya están solucionados los conflictos que tenía la aplicación con el registro de vehículos. Como ya he comentado antes, voy a explicar un poco más en profundidad los cambios que se han realizado para evitar confusiones.

Yo estaba encargado de dos subtareas dentro de la tarea #337, que era:

- Realizar un estilo del login / register y perfil coherente al resto de formularios de la aplicación
- Mejorar estilos de la aplicación que variaban estéticamente y hacía que el proyecto se viese realizado por partes.

A continuación, procedo a enseñar las pantallas del frontend que he modificado para dar una mejor apariencia a nuestra aplicación:

1. **Registrar vehículos**: tenía atributos en inglés, no tenían texto de ejemplo dentro de los inputs lo cual lo hacía poco intuitivo sobre todo para saber en qué formato se debían especificar las dimensiones (metros, centimetros, etc.), además de que el formulario variaba mucho estéticamente respecto otros en nuestra aplicación. Finalmente, ha quedado como en la captura adjunta:
![registrar vehiculos](https://github.com/Aparking/AparKing_Frontend/assets/73227047/619d55cb-06ee-4d40-893a-998b6935d8f5)

2. **Registrar garaje**: la estética del formulario no seguía el estilo de otras definidas en el proyecto, además de tener algunos inputs agobiados que impedían la lectura y campos donde no se añadía algún ejemplo sobre cómo rellenar el campo (mismo caso que con las dimensiones del formulario de registrar vehículos). Finalmente, ha quedado así tras aplicar los pertinentes cambios:
![registrar garaje 1](https://github.com/Aparking/AparKing_Frontend/assets/73227047/4c6b534d-0af7-4a25-8100-bd815dcf4311)
![registrar garaje 2](https://github.com/Aparking/AparKing_Frontend/assets/73227047/862b8b2f-9a54-4c88-9f2e-835d485f57a7)
![registrar garaje 3](https://github.com/Aparking/AparKing_Frontend/assets/73227047/315627f7-85d2-4b1b-968b-4545908147a8)

3. **Mis reservas**: he hecho un cambio menor añadiendo una X en la esquina superior izquierda para que sea más intuitivo cerrar el pop-up que se lanza al pulsar en mis reservas. Se puede visualizar en la captura siguiente:
![mis reservas](https://github.com/Aparking/AparKing_Frontend/assets/73227047/cacab01d-05d2-4887-a3c5-874cfb039baa)

4. **About Us**: he mejorado las fotografías ya que cada una tenía un tamaño distinto, además de especificar los roles que ha desempeñado cada uno y añadir tiktok como red social que faltaba. Finalmente, ha quedado así:
![about us 1](https://github.com/Aparking/AparKing_Frontend/assets/73227047/217431f1-00e9-468b-b9b9-06e7ae6c8cde)
![about us 2](https://github.com/Aparking/AparKing_Frontend/assets/73227047/08bd0810-0d28-4c56-8ad7-868874fabc5a)
![about us 3](https://github.com/Aparking/AparKing_Frontend/assets/73227047/f28caecf-8b71-4793-b494-71e603692edb)

5. **Mi perfil:** pequeños cambios estéticos para hacerla parecida a las pantallas de registro y login. Finalmente ha quedado así:
![mi perfil](https://github.com/Aparking/AparKing_Frontend/assets/73227047/2b5a0455-31a5-4b7a-a084-0164538a167e)

Por último, decir que todas estas pantallas se han creado teniendo desplegado el backend de la rama develop, con la rama actualizada hasta el día de hoy, lo que quiere decir que no he contemplado si habéis realizado algún que otro cambio por vuestra cuenta en alguna rama de trabajo de tarea personal.

Espero que con esto haya quedado más claro todo lo que acarrea esta PR. Si se necesitan aplicar nuevos cambios estéticos porque falte algo o se necesite mejorar alguna cosa, estoy encantado de leer vuestras propuestas y discutirlas para implementarlas :*

2024-05-15 16:40 UTC, 3ralon requested changes
He estado revisando el código y he detectado ciertas erratas. Dale una vueltecilla al código plis @virolialo.

2024-05-15 16:40 UTC, 3ralon commented on src/app/pages/login/login.page.scss
> +  .input-container {
He visto que has corregido el nombre de la clase de "conatiner" a "container". Está bien, pero asegurate de que todas las etiquetas html que usaban esa clase están cambiadas. He visto que no era así y te he marcado todas aquellas que he detectado.

2024-05-15 16:40 UTC, 3ralon commented on src/app/pages/login/login.page.scss
> +.error-container {
Este también lo has corregido y no está cambiado en todas las etiquetas html.

2024-05-15 16:40 UTC, 3ralon commented on src/app/pages/login/login.page.html
>          <div class="error-conatiner">
Corregir nombre de la clase.

2024-05-15 16:40 UTC, 3ralon commented on src/app/pages/login/login.page.html
>          <div class="error-conatiner">
Corregir nombre de la clase.

2024-05-15 16:40 UTC, 3ralon commented on src/app/components/rental/my-garages/my-garages.component.ts
Me ha gustado el cambio, sin embargo, la forma en la que se muestran "mis garajes" dejará de ser un pop-up, así que al hacer merge realmente esto se va a perder. Este cambio se puede ver [aquí](https://github.com/Aparking/AparKing_Backend/issues/340).

2024-05-15 16:40 UTC, 3ralon commented on src/app/components/rental/my-garages/my-garages.component.html
Aquí pasa lo mismo que en el comentario de "my-garages.component.ts". Si puedes haz un merge de develop en la rama del fix para traerte los últimos cambios y ver si afecta a algo más de los estilos.

2024-05-15 16:40 UTC, 3ralon commented on src/app/components/rental/garage-create/garage-create.component.html
> +                    <input class="form-input" label="Imagen" type="file" formControlName="image"
Revisa las etiquetas de clase que están en el html porque por ejemplo "form-input" no se está usando con los nuevos estilos.

2024-05-15 16:40 UTC, 3ralon commented on src/app/components/profile/profile.component.html
> -        <div class="error-conatiner">
Ten cuidado que has quitado el div de "error-container" que alinea bien los errores de validación en el formulario.

2024-05-16 15:35 UTC, virolialo commented on src/app/components/rental/my-garages/my-garages.component.html
Revisado, no afecta al resto de estilos de la aplicación.

2024-05-16 18:11 UTC, CarmenRuizPorcel commented
![image](https://github.com/Aparking/AparKing_Frontend/assets/72879200/aef2b440-3295-4359-8bb1-49e845e5af0f)
Hay alguna forma de que el logo se vea mejor, es que se ve un poco cutre. con el relleno en la rueda. Creo que @MarioArocaPaez tenia el logo en varios tamaños habla con el

2024-05-16 18:51 UTC, virolialo commented
> ![image](https://private-user-images.githubusercontent.com/72879200/331335484-aef2b440-3295-4359-8bb1-49e845e5af0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4ODU3MDIsIm5iZiI6MTcxNTg4NTQwMiwicGF0aCI6Ii83Mjg3OTIwMC8zMzEzMzU0ODQtYWVmMmI0NDAtMzI5NS00MzU5LThiYjEtNDllODQ1ZTVhZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE4NTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOGVhMzc0NGIwZDMwZjE2MjEyZGEzMjk2MzRiMWU2YzdjZmQ2MTJjYmZkMDNjMmNkOTE1ZjY0ZDc5YmY4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YQ2Rgy8mhkScOCCPQxIwuhj5u5_3Ne-wP7jBTP_CUcU) Hay alguna forma de que el logo se vea mejor, es que se ve un poco cutre. con el relleno en la rueda. Creo que @MarioArocaPaez tenia el logo en varios tamaños habla con el

Yo tambien pienso lo mismo, además cuando está en la etapa de verificación del registro, la imagen se achata y se ve regular.

De esta parte se encargó @silvglad , escribele para ver cómo se puede solucionar :)

2024-05-16 19:26 UTC, 3ralon requested changes
De acuerdo, @virolialo te he puesto unas cosillas tontas que he visto, el resto lo veo bien y he estado probando que vaya todo, así que corrige esas cositas y te doy el approve.

2024-05-16 19:26 UTC, 3ralon commented on src/app/components/parkingCesion/parkingCesion.component.html
> +        Matrcula coche a la que se cede: {{item[1].carModel}} <br>
Ten cuidado que se ha borrado la i de **Matrícula**

2024-05-16 19:26 UTC, 3ralon commented on src/app/components/profile/profile.component.html
> +          <span style="font-size: 14px;">Vehiculos</span>
Vehículos, cuidado que se te ha pasado la tilde.

2024-05-17 17:13 UTC, silvglad commented
> ![image](https://private-user-images.githubusercontent.com/72879200/331335484-aef2b440-3295-4359-8bb1-49e845e5af0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjU1NTYsIm5iZiI6MTcxNTk2NTI1NiwicGF0aCI6Ii83Mjg3OTIwMC8zMzEzMzU0ODQtYWVmMmI0NDAtMzI5NS00MzU5LThiYjEtNDllODQ1ZTVhZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE3MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MzU0NjE4YTA5ZDgzMjUwM2M3ZjZiMmJmM2NlNzRlYzM5M2JkMTExMjljOTNmYTlhOTdmY2UwMzlkNGQzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B2Z_kssVENfMer50Ag6BqGkfaudBTGGve6jvsH5_IJE) Hay alguna forma de que el logo se vea mejor, es que se ve un poco cutre. con el relleno en la rueda. Creo que @MarioArocaPaez tenia el logo en varios tamaños habla con el

Buenas, como no encontré la imagen original a mayor resolución intenté aumentar la resolución por IA. La rueda negra no me di cuenta ya que solo aparece en el dark mode y se camufla, intentaré ponerlo más bonito

2024-05-17 17:29 UTC, ivasansan1 requested changes
Resuelve esas faltas de ortografía, revisa los roles y las imágenes del logo

2024-05-17 17:29 UTC, ivasansan1 commented on src/app/components/rental/garage-create/garage-create.component.html
> +                  <ion-label position="floating">Titulo</ion-label>
Título lleva tilde cuidado

2024-05-17 17:29 UTC, ivasansan1 commented on src/app/components/rental/garage-create/garage-create.component.html
> +                    <ion-label position="floating">Descripcion imagen</ion-label>
Descripción lleva tilde

2024-05-17 17:29 UTC, ivasansan1 commented on src/app/pages/about-us/about-us-page.page.html
> +        <p>Frontend, Tester</p>
Falta GDPR

2024-05-17 17:44 UTC, virolialo commented
Revisados e implementados todos los cambios pedidos por Iván. Adicionalmente, he revisado de nuevo las pantallas para revisar más faltas de ortografía y he añadido otros cambios más.

2024-05-17 18:26 UTC, silvglad commented
He sustituido las dos imágenes de logo para dark y light mode. Me es imposible quitar la rueda del fondo sin cargarme la calidad de la imagen, así que comentadme si lo veis bien así
![aparkingCarDark](https://github.com/Aparking/AparKing_Frontend/assets/73229659/580ef3ef-9f8d-4ba2-ad25-1049ffa6d99f)
![carIcon](https://github.com/Aparking/AparKing_Frontend/assets/73229659/7919da74-970c-45eb-a707-6333f68ef3bd)

2024-05-17 18:28 UTC, CarmenRuizPorcel commented
@silvglad Habla con @MarioArocaPaez , el tenia el logo en distintos tamaños.

2024-05-17 18:29 UTC, CarmenRuizPorcel commented
![image](https://github.com/Aparking/AparKing_Frontend/assets/72879200/498894cb-4604-455a-b744-1777d4b549aa)
Se solapan las palabras arriba en la sección de mis reservas

2024-05-17 18:30 UTC, CarmenRuizPorcel commented
![image](https://github.com/Aparking/AparKing_Frontend/assets/72879200/8ddb7110-1c9c-44f0-9853-f72ea932d8ad)
Sección de tamaño y Tipo de secion vacío

2024-05-17 18:36 UTC, silvglad commented
> @silvglad Habla con @MarioArocaPaez , el tenia el logo en distintos tamaños.

Sí, pero solo tiene el original en menor calidad y con fondo blanco. Déjame saber si ves bien los logos como están ahora mismo

2024-05-17 19:05 UTC, CarmenRuizPorcel commented
> > @silvglad Habla con @MarioArocaPaez , el tenia el logo en distintos tamaños.
> 
> Sí, pero solo tiene el original en menor calidad y con fondo blanco. Déjame saber si ves bien los logos como están ahora mismo

A que tamaño lo quieres?

2024-05-17 19:25 UTC, silvglad commented
> > > @silvglad Habla con @MarioArocaPaez , el tenia el logo en distintos tamaños.
> > 
> > 
> > Sí, pero solo tiene el original en menor calidad y con fondo blanco. Déjame saber si ves bien los logos como están ahora mismo
> 
> A que tamaño lo quieres?

La imagen que me pudo conseguir Mario es esta, a 500x500. Lo ideal es que esté a 1000x1000 sin perder mucha calidad en el ai upscaling
![logo-removebg-preview](https://github.com/Aparking/AparKing_Frontend/assets/73229659/f854509b-09c6-4c20-b800-ff534d9938c9)

2024-05-17 19:50 UTC, ivasansan1 approved these changes

2024-05-19 11:08 UTC, CarmenRuizPorcel commented
yo voy a hacer una última revisión y la apruebo, entended que se tarde tando xq se hacen muuuchos cambios y muy significativos

2024-05-19 19:21 UTC, CarmenRuizPorcel approved these changes
Perfecto chicos, después de comprobarlo todo funciona todo genial

2024-05-19 19:41 UTC, MarioArocaPaez approved these changes
Ahora sí VAMOOOOOOOOOOOOO

2024-05-19 20:32 UTC, marvicmar approved these changes
Los cambios son correctos, buen trabajo.

2024-05-20 10:42 UTC, 3ralon approved these changes
Muy bonito mushas grasias. Bromas aparte, está genial, ya están todos los problemas solucionados, perfecto @virolialo.

2024-05-20 10:42 UTC, merged