Feat: IBAN attribute in profile
Aparking/AparKing_Frontend pull request #88
Opened 2024-05-15 12:18 UTC by ivasansan1

Añadido el atributo IBAN en el perfil.

Pensaba que ya hice esta pullRequest

2024-05-15 14:06 UTC, ivasansan1 commented
El último commit es el arreglo de la validación y al mergearlo con develop para que no de conflictos se ha cambiado el nombre del commit

2024-05-16 19:32 UTC, 3ralon requested changes
@ivasansan1 está bien el cambio, sólo elimíname ese archivo de la PR y todo ok :)

2024-05-16 19:32 UTC, 3ralon commented on .nx/cache/18.3.4-nx.win32-x64-msvc.node
@ivasansan1 puedes eliminar este archivo de configuración de la PR??

2024-05-17 18:44 UTC, ivasansan1 commented on .nx/cache/18.3.4-nx.win32-x64-msvc.node
ya esta removido @3ralon  :)

2024-05-18 08:58 UTC, laurolmer approved these changes
Se ve bien Iván buen trabajo

2024-05-18 11:21 UTC, 3ralon approved these changes
Perfecto Iván, te acepto el cambio!

2024-05-18 11:21 UTC, merged